apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.app.containerName }}
          image: docker.io/chaitu1812/r-{{ .Release.Name }}
          ports:
           - containerPort: {{ .Values.app.containerPort }}
              {{- if .Values.app.env }}
          env: {{- toYaml .Values.app.env | nindent 12 }}
           {{- end }}
