  {{- if .Values.app.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-load-schema
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      imagePullPolicy: Always
      containers:
        - name: {{ .Release.Name }}
          image: chaitu1812/r-loadschema
          env: {{- toYaml .Values.app.schema.env | nindent 12 }}
      restartPolicy: Never
  backoffLimit: 2
   {{- end }}